settings:
  title: ''
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Todos os servidores estão online'
  notAllmonitorsOperational: 'Todos os servidores estão offline'
  monitorLabelOperational: 'Operacional'
  monitorLabelNotOperational: 'Offline'
  monitorLabelNoData: 'Sem dados'
  dayInHistogramNoData: 'Sem dados'
  dayInHistogramOperational: 'OK'
  dayInHistogramNotOperational: ' incidente(s)' # xx incident(s) recorded

monitors:
  - id: main-site-movie
    name: Wovie
    description: 'Site principal.'
    url: 'https://zonimi.me/'
    method: GET
    expectStatus: 200
    followRedirect: false

  - id: main-player-movie
    name: Servidor de filmes/séries 01
    description: 'Este servidor é usado para stransmitir filmes e séries.'
    url: 'https://play.zonimi.me'
    method: GET
    expectStatus: 200

  - id: server1-player-movie
    name: Servidor de filmes/séries 02
    description: 'Este servidor é usado para stransmitir filmes e séries.'
    url: 'https://server-1.zonimi.me'
    method: GET
    expectStatus: 200
